name: MCCore
main: com.rit.sucy.MCCore
version: 1.52
author: Eniripsa96
description: A library of helpful functions to speed up and simplify plugin development for all developers.

commands:
  chat:
    description: chat controls for prefixes and display names
  board:
    description: scoreboard controls

permissions:
  core.board.cycle:
    description: allows a user to have their scoreboard cycle
    default: true
  core.board.list:
    description: allows a user to see a list of their active scoreboards
    default: true
  core.board.show:
    description: allows a user to change their scoreboard display
    default: true
  core.board.stop:
    description: allows a user to stop their scoreboard from cycling
    default: true
  core.board:
    description: access to all scoreboard commands
    default: op
    children:
      core.board.cycle: true
      core.board.show: true
      core.board.stop: true
  core.chat.list:
    description: displays a list of unlocked prefixes
    default: true
  core.chat.name:
    description: allows a user to change their display name
    default: op
  core.chat.prefix:
    description: allows a user to select a prefix
    default: true
  core.chat.reset:
    description: allows a user to reset their display name
    default: op
  core.chat:
    description: access to all chat commands
    default: op
    children:
      core.chat.list: true
      core.chat.name: true
      core.chat.prefix: true
      core.chat.reset: true
  core.*:
    description: anything and everything
    default: op
    children:
      core.board: true
      core.chat: true